title: PirateSec
email: pinpeepette@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Navigare tra le Acque della Sicurezza
baseurl: "/PirateSec" # the subpath of your site, e.g. /blog
url: "https://pinperepette.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Pinperepette
github_username:  Pinperepette

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links (aggiungi la sezione 'Corso Python' al menu)
navigation:
  - title: Home
    url: "{{ site.baseurl }}/"
  - title: Corso Python
    url: "{{ site.baseurl }}/corso-python/"
  - title: Corso Buffer Overflow
    url: "{{ site.baseurl }}/buffer-overflow/"
  - title: Corso Heap Overflow
    url: "{{ site.baseurl }}/heap-overflow/"
  - title: Blog
    url: "{{ site.baseurl }}/blog/"

# SEO settings
author: Pinperepette
lang: it

# Feed settings (se vuoi un feed RSS per il blog)
feed:
  path: feed.xml
